---
title: " A Statistical Analysis: Heart Disease Predection"
author: "Group Members: TY Punleu, Song Kimleangchhay Khy Pichsereyvathanak, Ouk Vatana, Srey Sitharath"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  pdf_document:
    toc: true
    number_sections: true
    latex_engine: xelatex
  html_document:
    toc: true
    code_folding: hide
---

```{r setup, include=FALSE}
# This chunk sets global options for the notebook.
# It ensures all necessary packages are loaded and controls how code/output is displayed.
knitr::opts_chunk$set(
  echo = TRUE,      # Show the code in the final report
  warning = FALSE,  # Hide warnings
  message = FALSE,  # Hide messages
  fig.width = 7,    # Default width for figures
  fig.height = 5,   # Default height for figures
  cache = FALSE     # Set to TRUE only if processing time is long
)
```

```{r}
# TODO - Load essential libraries

```

# 1.Introduction



## 1.1. Problem Statement

## 1.2. Research Objectives

## 1.3. Research Questions 


# 2.  Dataset 


# 3.  Methodology and Data Preprocessing

## 3.1. Data Acquisition and Cleaning


## 3.2. Descriptive Statistic


## 3.3. Inferential Statistic



## 3.4. Correlation and Regression Analysis


## 3.5. Intepretation and Recommendation 

